/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PcExample {
    }
}
declare global {
    interface HTMLPcExampleElement extends Components.PcExample, HTMLStencilElement {
    }
    var HTMLPcExampleElement: {
        prototype: HTMLPcExampleElement;
        new (): HTMLPcExampleElement;
    };
    interface HTMLElementTagNameMap {
        "pc-example": HTMLPcExampleElement;
    }
}
declare namespace LocalJSX {
    interface PcExample {
    }
    interface IntrinsicElements {
        "pc-example": PcExample & JSXBase.HTMLAttributes<HTMLPcExampleElement>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pc-example": LocalJSX.PcExample & JSXBase.HTMLAttributes<HTMLPcExampleElement>;
        }
    }
}